name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: starter/backend
        run: docker build --tag=mp-backend:latest .

      - name: Deploy Kubernetes manifests
        working-directory: starter/backend
        run: kubectl apply -k k8s/
